Quadratic_Solver2: Quadratic_Solver2.o
	g++ Quadratic_Solver2.o -o Quadratic_Solver2
Quadratic_Solver2.o: Quadratic_Solver2.cpp
	g++ -c Quadratic_Solver2.cpp -o Quadratic_Solver2.o
run: Quadratic_Solver2
	./Quadratic_Solver2
clean:
	rm -f Quadratic_Solver2.o Quadratic_Solver2.exe
