Problem1 HW Bayu : Probelm1 HW Bayu . o
g ++ Problem1 HW Bayu . o -o Problem1 HW Bayu

Problem1 HW Bayu . o : Problem1 HW Bayu.cpp
g++ -c Problem1 HW Bayu.cpp -o Problem1 HW Bayu.o

dump:
objdump -d Problem1 HW Bayu > Problem1 HW Bayu.asm

clean:
rm -f Problem1 HW Bayu.o Problem1 HW Bayu

run: Problem1 HW Bayu
./Problem1 HW Bayu
