Payslip_Employee: Payslip_Employee.o
	g++ Payslip_Employee.o -o Payslip_Employee
Payslip_Employee.o: Payslip_Employee.cpp
	g++ -c Payslip_Employee.cpp -o Payslip_Employee.o
run: Payslip_Employee
	./Payslip_Employee
clean:
	rm -f Payslip_Employee.o Payslip_Employee.exe
