Quadratic_Solver: Quadratic_Solver.o
	g++ Quadratic_Solver.o -o Quadratic_Solver
Quadratic_Solver.o: Quadratic_Solver.cpp
	g++ -c Quadratic_Solver.cpp -o Quadratic_Solver.o
run: Quadratic_Solver
	./Quadratic_Solver
clean:
	rm -f Quadratic_Solver.o Quadratic_Solver.exe
